# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.epdg0.useDHCP = lib.mkDefault true;
  # networking.interfaces.epdg1.useDHCP = lib.mkDefault true;
  # networking.interfaces.epdg2.useDHCP = lib.mkDefault true;
  # networking.interfaces.epdg3.useDHCP = lib.mkDefault true;
  # networking.interfaces.epdg4.useDHCP = lib.mkDefault true;
  # networking.interfaces.ip6tnl0.useDHCP = lib.mkDefault true;
  # networking.interfaces.p2p0.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet1.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet2.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet3.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet4.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet5.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet6.useDHCP = lib.mkDefault true;
  # networking.interfaces.rmnet7.useDHCP = lib.mkDefault true;
  # networking.interfaces.sit0.useDHCP = lib.mkDefault true;
  # networking.interfaces.swlan0.useDHCP = lib.mkDefault true;
  # networking.interfaces.umts_dm0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
